-- clean
DROP TABLE IF EXISTS employee;
DROP TABLE IF EXISTS department;

-- schema
CREATE TABLE department(
    department_name text PRIMARY KEY,
    parent text NULL REFERENCES department(department_name)
);

CREATE TABLE employee(
    department_name text NOT NULL REFERENCES department,
    employee_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    salary int NOT NULL
);